// swift-tools-version:6.0

import Foundation
import PackageDescription

let FFIbinaryTarget: PackageDescription.Target
// If the environment variable `LOCAL_BUILD` is set to any value, the packages uses
// a local reference to the XCFramework file (built from `./scripts/build-xcframework.sh`)
// rather than the previous released version.
//
// The script `./scripts/build-xcframework.sh` _does_ expect that you have Rust
// installed locally in order to function.
if ProcessInfo.processInfo.environment["LOCAL_BUILD"] != nil {
    // We are using a local file reference to an XCFramework, which is functional
    // on the tags for this package because the XCFramework.zip file is committed with
    // those specific release points. This does, however, cause a few awkward issues,
    // in particular it means that swift-docc-plugin doesn't operate correctly as the
    // process to retrieve the symbols from this and the XCFramework fails within
    // Swift Package Manager. Building documentation within Xcode works perfectly fine,
    // but if you're attempting to generate HTML documentation, use the script
    // `./scripts/build-ghpages-docs.sh`.
    FFIbinaryTarget = .binaryTarget(
        name: "automergeFFI",
        path: "./automergeFFI.xcframework"
    )
} else {
    FFIbinaryTarget = .binaryTarget(
        name: "automergeFFI",
        url: "https://github.com/automerge/automerge-swift/releases/download/0.7.2/automergeFFI.xcframework.zip",
        checksum: "10245378e74229b026f689b039d7df3cf17aeed353706d5f420dfd164f283a86"
    )
}

let package = Package(
    name: "Automerge",
    platforms: [.iOS(.v13), .macOS(.v10_15), .visionOS(.v1)],
    products: [
        .library(name: "Automerge", targets: ["Automerge", "AutomergeUtilities"]),
    ],
    targets: [
        FFIbinaryTarget,
        .target(
            name: "AutomergeUniffi",
            dependencies: [
                // On Apple platforms, this links the core Rust library through XCFramework.
                // On other platforms (such as WASM), end users will need to build the library
                // themselves and link it through the "swift build -Xlinker path/to/libuniffi_automerge.a"
                // for example: cargo build --manifest-path rust/Cargo.toml --target wasm32-wasip1 --release
                .target(name: "automergeFFI", condition: .when(platforms: [
                    .iOS, .macOS, .macCatalyst, .tvOS, .watchOS, .visionOS,
                ])),
                // The dependency on _CAutomergeUniffi gives the WebAssembly linker a place to link in
                // the automergeFFI target when the XCFramework binary target isn't available.
                .target(name: "_CAutomergeUniffi", condition: .when(platforms: [.wasi, .linux])),
            ],
            path: "./AutomergeUniffi",
            // automerge.swift is generated by UniFFI and isn't Swift 6 concurrency-clean,
            // so it stays in the Swift 5 language mode rather than being hand-edited.
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .systemLibrary(name: "_CAutomergeUniffi"),
        .target(
            name: "Automerge",
            dependencies: ["AutomergeUniffi"]
        ),
        .target(
            name: "AutomergeUtilities",
            dependencies: ["Automerge"]
        ),
        .testTarget(
            name: "AutomergeTests",
            dependencies: ["Automerge", "AutomergeUtilities"],
            exclude: ["Fixtures"]
        ),
    ]
)
